DELETE FROM `#__categories` WHERE `extension` = 'com_catalogue';
DROP TABLE IF EXISTS `#__catalogue_attr`;
DROP TABLE IF EXISTS `#__catalogue_attr_price`;
DROP TABLE IF EXISTS `#__catalogue_attrdir`;
DROP TABLE IF EXISTS `#__catalogue_attrdir_category`;
DROP TABLE IF EXISTS `#__catalogue_cart`;
DROP TABLE IF EXISTS `#__catalogue_country`;
DROP TABLE IF EXISTS `#__catalogue_item`;
DROP TABLE IF EXISTS `#__catalogue_item_review`;
DROP TABLE IF EXISTS `#__catalogue_manufacturer`;
DROP TABLE IF EXISTS `#__catalogue_order`;
